/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Produtos;
import model.dao.ProdutoDA0;
//PEGAR VAL0R PRA SELECI0NAR
/**
 *
 * @author PC TESTE
 */
public class ViewJTable extends javax.swing.JFrame {

    public ViewJTable() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        jTProdutos.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDA0 dao = new ProdutoDA0();

        for (Produtos p : dao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getPreço()

            });

        }

    }
    public void JTablesearch(String desc){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDA0 pdao = new ProdutoDA0();
        
        for(Produtos p: pdao.search(desc)){
            
            modelo.addRow(new Object[]{
                
                
                p.getId(),p.getDescricao(),p.getQtd(),p.getPreço()
                
            });
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        textQtd = new javax.swing.JTextField();
        textPreco = new javax.swing.JTextField();
        button_cadastrat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        button_editor = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preço:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 186, -1));

        textQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQtdActionPerformed(evt);
            }
        });
        getContentPane().add(textQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 186, -1));

        textPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(textPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 200, -1));

        button_cadastrat.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC TESTE\\Desktop\\Netbeans and IMG\\Sistema\\src\\imagens\\save.png")); // NOI18N
        button_cadastrat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_cadastratMouseEntered(evt);
            }
        });
        button_cadastrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cadastratActionPerformed(evt);
            }
        });
        getContentPane().add(button_cadastrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 40));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC TESTE\\Desktop\\Netbeans and IMG\\Sistema\\src\\imagens\\editar.png")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 60, 60));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC TESTE\\Desktop\\Netbeans and IMG\\Sistema\\src\\imagens\\trash.png")); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 80, 50));

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jTProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 850, 280));

        button_editor.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC TESTE\\Desktop\\Netbeans and IMG\\Sistema\\src\\imagens\\search.png")); // NOI18N
        button_editor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_editorMouseEntered(evt);
            }
        });
        button_editor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editorActionPerformed(evt);
            }
        });
        getContentPane().add(button_editor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 60, 50));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 186, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel4.setFont(new java.awt.Font("Gregor Miller's Friends Font", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastrar Produto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jframe.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -20, 1090, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void textQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQtdActionPerformed

    private void textPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecoActionPerformed

    private void button_cadastratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cadastratActionPerformed
        if (txtDesc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira a Descrição");
            txtDesc.requestFocusInWindow();
            return;
        }
        if (textQtd.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira a Quantidade");
            textQtd.requestFocusInWindow();
            return;
        }
        if (textPreco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o Preço");
            textPreco.requestFocusInWindow();
            return;
        }

        /*DefaultTableModel dtmProdutos= (DefaultTableModel) jTProdutos.getModel();
    Object[] dados = {txtDesc.getText(),textQtd.getText(),textPreco.getText()};
    dtmProdutos.addRow(dados);* ------------> sem banco de dados*/
        Produtos p = new Produtos();
        ProdutoDA0 dao = new ProdutoDA0();

        p.setDescricao(txtDesc.getText());
        p.setQtd(Integer.parseInt(textQtd.getText()));
        p.setPreço(Double.parseDouble(textPreco.getText()));

        dao.create(p);

        readJTable();

        txtDesc.setText("");
        textQtd.setText("");
        textPreco.setText("");
        txtDesc.requestFocusInWindow();


    }//GEN-LAST:event_button_cadastratActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jTProdutos.getSelectedRow() != -1) {

            Produtos p = new Produtos();
            ProdutoDA0 dao = new ProdutoDA0();

            p.setDescricao(txtDesc.getText());
            p.setQtd(Integer.parseInt(textQtd.getText()));
            p.setPreço(Double.parseDouble(textPreco.getText()));
            p.setId((int) jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0));
            dao.update(p);

            readJTable();

            txtDesc.setText("");
            textQtd.setText("");
            textPreco.setText("");
            txtDesc.requestFocusInWindow();

        } else {

            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // System.out.println("Linha selecionada"+ jTProdutos.getSelectedRow() );

        if (jTProdutos.getSelectedRow() != -1) {

            Produtos p = new Produtos();                                                                                   //DefaultTableModel dtmProdutos = (DefaultTableModel) jTProdutos.getModel();
            ProdutoDA0 dao = new ProdutoDA0();                                                                                    //dtmProdutos.removeRow(jTProdutos.getSelectedRow());
            
            
           
            p.setId((int) jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0));
            dao.delete(p);

            readJTable();

            txtDesc.setText("");
            textQtd.setText("");
            textPreco.setText("");
            txtDesc.requestFocusInWindow();

        } else {

            JOptionPane.showMessageDialog(null, "Selecione um produto para deletar");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked

        if (jTProdutos.getSelectedRow() != -1) {

            txtDesc.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            textQtd.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            textPreco.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());

        } else {

            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar");
        }


    }//GEN-LAST:event_jTProdutosMouseClicked

    private void jTProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProdutosKeyReleased
        if (jTProdutos.getSelectedRow() != -1) { //WHATEVER KEY RELEASED 0R M0USE CLICKED

            txtDesc.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            textQtd.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            textPreco.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());

        } else {

            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar");
        }
    }//GEN-LAST:event_jTProdutosKeyReleased

    private void button_editorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editorActionPerformed
      
        JTablesearch(txtBuscar.getText());
        
        
    }//GEN-LAST:event_button_editorActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ViewHome vw = new ViewHome();
       vw.show();
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        String string = "Voltar";
        jButton1.setToolTipText(string);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void button_cadastratMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cadastratMouseEntered
        String string = "Cadastrar";
        jButton1.setToolTipText(string);        // TODO add your handling code here:
    }//GEN-LAST:event_button_cadastratMouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        String string = "Atualizar";
        jButton1.setToolTipText(string);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        String string = "Excluir";
        jButton1.setToolTipText(string);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void button_editorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_editorMouseEntered
        String string = "Procurar Produto";
        jButton1.setToolTipText(string);        // TODO add your handling code here:
    }//GEN-LAST:event_button_editorMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cadastrat;
    private javax.swing.JButton button_editor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTextField textPreco;
    private javax.swing.JTextField textQtd;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDesc;
    // End of variables declaration//GEN-END:variables
}
